### ISSUE TITLE
[Endpoint] GET api/activity/:id

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#11]
Retrieve the complete activity document by their id

Route: `api/activity/:id`
Method: `GET`

- No authorization needed yet
- Documentation via swagger
- Return the whole document
- Populate the employee property
    - name + lastName
    - employeeNumber
    - email
    - phoneNumber

**Comment by jaime-human** [comment]
@pawap90 what do you mean by "Populate the employee property"?

**Comment by pawap90** [comment]
@jaime-human The employee property is a reference to another collection, meaning that the contents of the employee document are not embedded within the activity. Therefore, if we want to retrieve the related employee information along with the activity document we need to "tell" mongoose that we want to populate that information from another collection.

It would look something like this
```js
await ActivityModel.findById(id)
             .populate('employee', 'name lastName employeeNumber email phoneNumber');
```

You'll notice that without that last line, the query will only return the employee id.

More info here:
https://mongoosejs.com/docs/populate.html#field-selection

**Comment by jaime-human** [comment]
Thanks @pawap90 ! Now i understand in this situation how to use it because its a GET method. If you can help me in the post, it would be nice
