### ISSUE TITLE
[Endpoint] POST api/member

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#13]
Endpoint to create members of the gym

Route: `api/member`
Method: `POST`

Body properties:
```
- name (string - required)
- lastName (string - required)
- email (string - required)
- address (string - required)
- dateOfBirth (Date - required)
- dni (string - required)
- emergencyPhoneNumber (string - required)
```

- No authorization needed yet.
- The memberNumber must be auto-numeric and generated by the backend.
- The entryDate must be auto-generated as the moment the document is inserted.
- Documentation via swagger.

Also, create the model schema for "member":
```
- persona (persona model embedded - required)
- memberNumber  (number - required)
- entryDate (Date - required)
- dni (string - required)
- emergencyPhoneNumber (string - required)
- medicalInformation (embedded - optional)
    - certificateIssuedDate (date - required)
    - certificateIssuerMedicalLicense (string - required)
    - observations (string - optional)
    - hasHearthProblems (bool - required)
    - hasAsthma(bool - required)
    - hasDiabetes (bool - required)
    - smokes (bool - required)
```

> Note: The medical information will be handled by a differente set of endpoints under the route: `api/member/:id/medical-information`

**Comment by jaime-human** [comment]
@pawap90 , im planning to rename "entryDate" to "createDate", because thats the name that was used in the `employee.model.js`.

And the createDate is the one that is set with a `Date.now()`.

Is this OK?

**Comment by pawap90** [comment]
> @pawap90 , im planning to rename "entryDate" to "createDate", because thats the name that was used in the `employee.model.js`.
> 
> And the createDate is the one that is set with a `Date.now()`.
> 
> Is this OK?

Actually, the employee model has 2 dates:
- entryDate is the one that's defined by the admin to specify when will the employee start working on the gym, their "first day".
- createDate is the system-defined date that allows us to sort employees by the date they were entered to the system, which may be different than the entry date.

In this case it should be entryDate because it's a "human defined date" that tells us when the member starts using the gym's services.

**Comment by jaime-human** [comment]
Great! Thank you, the explanation is very clear 👍
