### ISSUE TITLE
[Endpoint] DELETE api/member/:id

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#15]
Endpoint to delete a member of the gym by id

Route: `api/member/:id`
Method: `DELETE`

- No authorization needed yet.
- Documentation via swagger.

**Comment by jaime-human** [comment]
Are we going to make physical deletes or logical deletes?

In my opinion, just because it will be easier to code everything and to check faster the effects on the DB, i would rather make physical deletes

**Comment by pawap90** [comment]
@jaime-human I'm doing physical deletes, for now, to keep things simple. We can replace them with logical deletes if needed later on.
