### ISSUE TITLE
[Endpoint] GET api/member/payment

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#48]
Method: `GET`

Route: `api/member/payment`

More info:
- Retrieve the complete list of payments
- For each plan return the whole document 
- Populate the following `member` properties
  - memberNumber
  - name
  - lastName
- Populate the following `plan` properties
  - name
- Sort results by date

**Comment by jaime-human** [comment]
Hi there, im confused in this issue.

because of this 2 items:
- For each plan return the whole document

- Populate the following plan properties:  name


Should i make a json with a structure like this one?

{
 payments: [
    {
         plan: 'plan-name',
         ~all other attributes here~
     } 
  ],
 plans: [
     {
         ~all plans attributes here~
     }
  ]
}

**Comment by pawap90** [comment]
@jaime-human That was just a mistake, probably caused by copy paste. I was just reviewing your PR and I think it's ready to merge.
