### ISSUE TITLE
Store Gym legal data on backend

### ISSUE THREAD

**Issue by jaime-human** [mauro-codes/uade-gym-api#79]
Save in a constant in the backend, the next legal information about the GYM:
	* CUIT: '12-12345678-9'
	* Punto de venta: '00001'
	* Ingresos brutos: '12-12345678-9'
	* Fecha de inicio de actividades: '07-01-2020' (MM/dd/yyyy)
	* LegalName (Razón social): 'Gimnasio A'
	* LegalAddress: 'Calle A 1234 - Ciudad de buenos aires'
	* Condición frente al IVA: 'Responsable Inscripto'
	* Ingresos brutos: '12-12345678-9'

**Comment by jaime-human** [comment]
@pawap90 should this be a service returning the legal data?

or should this be a file with constants that will be used in other parts of the app?

is there any keyworkd that you could tell me so that I understand technically what you are expecting from this?

**Comment by pawap90** [comment]
@jaime-human We'll only be needing the data as a constant, for now. There's no need for an endpoint yet. 
I'd create a component for this, maybe called "legal-data" 🤔, that has only a module that returns the object described in the issue.
