### ISSUE TITLE
[Endpoint] POST api/member/:id/invoice

### ISSUE THREAD

**Issue by jaime-human** [mauro-codes/uade-gym-api#81]
@pawap90 en el parrafo de abajo, esta diciendo que tiene que haber un `invoice.service.js`?

Reutiliza el mismo servicio que GET api/member/:id/invoice/preview para obtener el documento Invoice incompleta.
Luego completa el documento combinando estos datos con los adicionales enviados en el body.

**Body:**
	- expirationDate
	- invoiceType (string "Factura A", "Factura C", etc).

La propiedad paymentDate se setea en null.

**Modelo Invoice:**
	- invoiceCode (00000001)
	- startDate
	- endDate
	- expirationDate
	- createDate (default now)
	- invoiceType (string "Factura A", "Factura C", etc)
	- sender
		- cuit
		- sellingAddressCode (punto de venta)
		- grossIncome (ingresos brutos)
		- activityStartDate (fecha de inicio de actividades)
		- legalName (Razón social)
		- legalAddress
		- vatCondition (condición frente al IVA)
	- receiver
		- name
		- lastName
		- cuit
		- address
	- details (array)
		- name
		- quantity (default 1)
		- subtotal (number)
		- unitPrice (number)
	- subtotal (number)
	- total (number)
	- status (string - default: 'pending')
	- paymentDate (Date - nullable)

**Comment by pawap90** [comment]
@jaime-human creo que sería lo mejor, para mantener los temas separados y que el codigo de member.service.js no se extienda demasiado.

**Comment by jaime-human** [comment]
@pawap90 que atributos vendrian en el body y que atributos se generarian u obtendrian de otras formas?

Queres encargarte vos de este issue y yo me encargo de otros? porque no estoy seguro de entenderlo. O si queres, me podrias agregar info? Pasa q para agregarme la info, por ahi ya preferis hacerlo vos.

Como prefieras!

**Comment by jaime-human** [comment]
@pawap90 
startDate y endDate entonces no deberia ponerlos en el modelo? porque son dato del modelo del plan como dice en el endpoint:
https://github.com/mauro-codes/uade-gym-api/issues/80

**Comment by jaime-human** [comment]
@pawap90 could it be that this endpoint should be for employees instead of members?

**Comment by jaime-human** [comment]
@pawap90 todos los datos tienen que permanecer en la BBDD a pesar de que podrian ser populados?

Esto es para dejar un buen registro de los datos en caso de que en el futuro se modifiquen?

Hay algo que estoy interpretando mal?

**Comment by pawap90** [comment]
El modelo del plan es el q está definido debajo de "Model" en este issue, y si, incluye el startDate y endDate.
Lo que viene en el body es lo que está definido en este issue debajo de "Body". 
El invoice code debería ser creado igual que en el employee y member. Pero solo en el Post (no en en preview).
Los datos se deben agregar igual aunque se puedan popular de otros modelos, porque la factura es como un snapshot de in momento dado. O sea, si cambia el precio del plan o el nombre del socio no quiero q cambien todas mis facturas.

**Comment by jaime-human** [comment]
@pawap90 

Im planning to set the startDate as the current date, that may be slightly incorrect but for now i think its okay.

If theres a better way that i should code, please let me know.
