### ISSUE TITLE
Credit card integration

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#88]
Payments should execute a credit card transaction

Endpoint: PUT api/member/:memberId/invoice/:invoiceId

Depends on #82

**Comment by jaime-human** [comment]
@pawap90 paula! if you are okay with it and its not too messy to ask for the requirements, i would enjoy coding one of the issues for the integration with the bank or the credit card.

I also thought that I could even use as guide the other issue that you could take care about. In that way, I could have fun but using the same architecture that you have planned for this.

If I wasnt clear enough about my ideas please let me know

**Comment by pawap90** [comment]
@jaime-human My idea was to solve this issue myself so it can be used as an example for other external services' integrations. Would you like to take over this one instead: #89 ? I plan to solve #88 today, so you can get started with #89 once that's done.
In the meantime, there are a few other issues to take care of besides those two.
