### ISSUE TITLE
[Endpoint] GET api/employee/job-title

### ISSUE THREAD

**Issue by pawap90** [mauro-codes/uade-gym-api#93]
Method: `GET`
Route: `api/employee/job-title`

Retrieves a list of job titles with their associated salary.

This list of job titles is not stored on database (for now). It should be an array defined on a new file: `components/employee/job-title.js`. 

# Job Titles
supervisor
**value**: 46188

sportsCoordinator
**value**: 42773 

areaCoordinator
**value**: 40751

physicalEducationTeacher
**value**: 40000

instructorAndCoach
**value**: 38400

lifeguards
**value**: 52409

maintenanceManager
**value**: 46776 

administrativeStaff
**value**: 38628

receptionistOrSeller
**value**: 35206

accessControl
**value**: 35017

auxiliary
**value**: 35657

cleaningStaff
**value**: 33371

# Response
```js
[
    {
        "name": "supervisor",
        "basicSalary": 46188
    },

    {
        "name": "sportsCoordinator",
        "basicSalary": 42773 
    },
    // ...
]
```

**Comment by jaime-human** [comment]
@pawap90 Would you like me to name it `gross-salary` instead of `value`? I think its more clear that way
